Repository vinicarvalhosantos/fawkes-api, pull requests merged in 2022-02, with the labels that each got.

#2 Created model reward
  database/connect.go
  go.mod
  go.sum
  internal/model/reward.go
Labels: feature

#4 Created the reward create route
  go.mod
  go.sum
  internal/handler/reward/rewardHandler.go
  internal/model/reward.go
  internal/model/user.go
  internal/route/reward/reward.go
  internal/route/user/auth/auth.go
  internal/route/user/user.go
  router/v1/v1.go
Labels: feature

#5 Create the update user handler
  internal/handler/user/userHandler.go
  internal/route/user/user.go
Labels: feature

#6 Create twitch user login integration
  go.mod
  go.sum
  internal/handler/user/auth/authHandler.go
  internal/route/auth/auth.go
  internal/route/user/user.go
  router/v1/v1.go
Labels: feature, Improvment

#7 Created the functionality to get all rewards , get by id , change and…
  internal/handler/reward/rewardHandler.go
  internal/model/reward.go
  internal/route/reward/reward.go
  internal/util/constant/constant.go
Labels: feature

#8 Fix code smells and change auth path
  internal/handler/auth/authHandler.go
  internal/route/auth/auth.go
  internal/util/constant/constant.go
Labels: Improvment

#9 Create address model unit tests
  .gitignore
  internal/handler/auth/authHandler.go
  internal/model/address_test.go
  internal/util/constant/constant.go
  internal/util/encrypt/encrypt.go
Labels: Improvment

#10 Created new reward management routes.
  .gitignore
  internal/handler/address/addressHandler.go
  internal/handler/reward/rewardHandler.go
  internal/route/auth/auth.go
  internal/route/reward/reward.go
  internal/util/constant/constant.go
Labels: feature
